# project will be built in the Android environment
language:  android
android:
  components:
     # The BuildTools version used by the project
    - build-tools-28.0.3
    # The SDK version used to compile the project
    - android-28
  sudo: required
  before_install:
    - chmod +x gradlew
  script:
    - ./gradlew clean build -i --continue
